name: desk_zoho_chat
description: Zoho Desk Flutter Package For In-app support.
version: 0.0.1
homepage: https://www.github.com/ibnyahyah/desk_zoho_chat

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.whitecoode.desk_zoho_chat
        pluginClass: DeskZohoChatPlugin
      ios:
        pluginClass: DeskZohoChatPlugin

  assets:
    - packages/desk_zoho_chat/assets/index.html
    - packages/desk_zoho_chat/assets/index2.html
